Program: exp
	./run

exp: Makefile example.c compact_enc.c compact_enc.h ../mceliece6688128/nist/rng.c ../mceliece6688128/nist/rng.h ../mceliece6688128/randombytes.h ../mceliece6688128/benes.c ../mceliece6688128/bm.c ../mceliece6688128/controlbits.c ../mceliece6688128/decrypt.c ../mceliece6688128/encrypt.c ../mceliece6688128/gf.c ../mceliece6688128/operations.c ../mceliece6688128/pk_gen.c ../mceliece6688128/root.c ../mceliece6688128/sk_gen.c ../mceliece6688128/synd.c ../mceliece6688128/transpose.c ../mceliece6688128/util.c    
	./build

time:
	./build_time
	./timing
