Program: exp
	./run

exp: Makefile example.c ../mceliece348864/nist/rng.c ../mceliece348864/nist/rng.h ../mceliece348864/randombytes.h ../mceliece348864/benes.c ../mceliece348864/bm.c ../mceliece348864/controlbits.c ../mceliece348864/decrypt.c ../mceliece348864/encrypt.c ../mceliece348864/gf.c ../mceliece348864/operations.c ../mceliece348864/pk_gen.c ../mceliece348864/root.c ../mceliece348864/sk_gen.c ../mceliece348864/synd.c ../mceliece348864/transpose.c ../mceliece348864/util.c    
	./build
